#!/bin/bash

PUBKEY="{{ .pubkey }}"

function check_dep() {
    if ! command -v $1 >/dev/null 2>&1; then
        echo "$1 is not installed"
    fi
}

while read -r util ; do
    if  [[ ! -z "$util" ]] ; then
        check_dep $util
    fi
done << EOF
{{ .depends }}
EOF

if ! grep ~/.ssh/authorized_keys "${PUBKEY}" 1>/dev/null 2>&1 ; then
    mkdir -p ~/.ssh
    echo ${PUBKEY} >> ~/.ssh/authorized_keys
fi
